INSERT INTO professor (nome, usuario, senha) VALUES
  ('professor1', 'professor1', 'senha1'),
  ('professor2', 'professor2', 'senha2'),
  ('professor3', 'professor3', 'senha3'),
  ('professor4', 'professor4', 'senha4'),
  ('professor5', 'professor5', 'senha5'),
  ('professor6', 'professor6', 'senha6');

INSERT INTO aluno (id_professor, nome, usuario, senha, total_pontos, fase) VALUES
  (1, 'aluno1', 'professor1', 'senha1', 1, 1),
  (1, 'aluno2', 'professor2', 'senha2', 3, 1),
  (2, 'aluno3', 'professor3', 'senha3', 4, 1),
  (2, 'aluno4', 'professor4', 'senha4', 0, 1),
  (3, 'aluno5', 'professor5', 'senha5', 3, 1),
  (6, 'aluno6', 'professor7', 'senha7', 0, 1),
  (5, 'aluno7', 'professor8', 'senha8', 0, 1),
  (6, 'aluno8', 'professor9', 'senha9', 0, 1),
  (6, 'aluno9', 'professor10', 'senha10', 10, 1);

INSERT INTO bioma (nome) VALUES
  ('Oceano'),
  ('Campo'),
  ('Deserto'),
  ('Floresta');

INSERT INTO animal (id_bioma, nome, imagem) VALUES
  (1, 'Água-viva', 'agua_viva'),
  (1, 'Arraia', 'arraia'),
  (1, 'Bagre', 'bagre'),
  (1, 'Baleia Azul', 'baleia_azul'),
  (1, 'Baleia Orca', 'baleia_orca'),
  (1, 'Camarão', 'camarao'),
  (1, 'Cavalo-marinho', 'cavalo_marinho'),
  (1, 'Estrela-do-mar', 'estrela_do_mar'),
  (1, 'Foca', 'foca'),
  (1, 'Golfinho', 'golfinho'),
  (1, 'Peixe-palhaço', 'peixe_palhaço'),
  (1, 'Polvo', 'polvo'),
  (1, 'Tartaruga', 'tartaruga'),
  (1, 'Tubarão', 'tubarao'),

  (2, 'Abelha', 'abelha'),
  (2, 'Águia', 'aguia'),
  (2, 'Besouro', 'besouro'),
  (2, 'Bode', 'bode'),
  (2, 'Burro', 'burro'),
  (2, 'Camundongo', 'camundongo'),
  (2, 'Canguru', 'canguru'),
  (2, 'Cavalo', 'cavalo'),
  (2, 'Cervo', 'cervo'),
  (2, 'Coelho', 'coelho'),
  (2, 'Cutia', 'cutia'),
  (2, 'Girafa', 'girafa'),
  (2, 'Lobo-Guara', 'lobo_guara'),
  (2, 'Ovelha', 'ovelha'),
  
  (3, 'Avestruz', 'avestruz'),
  (3, 'Cágado', 'cagado'),
  (3, 'Camaleão', 'camaleao'),
  (3, 'Cobra', 'cobra'),
  (3, 'Elefante', 'elefante'),
  (3, 'Escorpião', 'escorpiao'),
  (3, 'Hiena', 'hiena'),
  (3, 'Hipopotamo', 'hipopotamo'),
  (3, 'Iguana', 'iguana'),
  (3, 'Javali', 'javali'),
  (3, 'Lagarto', 'lagarto'),
  (3, 'Leão', 'leao'),
  (3, 'Rinoceronte', 'rinoceronte'),
  (3, 'Suricato', 'suricato'),
  (3, 'Zebra', 'zebra'),

  (4, 'Arara', 'arara'),
  (4, 'Bicho-Preguiça', 'bicho_preguica'),
  (4, 'Coala', 'coala'),
  (4, 'Coruja', 'coruja'),
  (4, 'Doninha', 'doninha'),
  (4, 'Esquilo', 'esquilo'),
  (4, 'Gambá', 'gamba'),
  (4, 'Gorila', 'gorila'),
  (4, 'Guaxinim', 'guaxinim'),
  (4, 'Jaguatirica', 'jaguatirica'),
  (4, 'Lemure', 'lemure'),
  (4, 'Macaco', 'macaco'),
  (4, 'Mico-Leão', 'mico_leao'),
  (4, 'Morcego', 'morcego'),
  (4, 'Onça Pintada', 'onca_pintada');

INSERT INTO dificuldade (numero_cartas, tempo_limite) VALUES
  (6, 60),
  (10, 90),
  (14, 120);

INSERT INTO partida (id_aluno, id_bioma, id_dificuldade, status) VALUES
  (1, 1, 3, 'FINALIZADO'),
  (1, 2, 1, 'FINALIZADO'),
  (2, 1, 3, 'FINALIZADO'),
  (5, 4, 1, 'FINALIZADO'),
  (3, 4, 2, 'FINALIZADO'),
  (4, 4, 1, 'FINALIZADO'),
  (3, 4, 2, 'FINALIZADO'),
  (4, 4, 3, 'FINALIZADO'),
  (1, 4, 3, 'FINALIZADO'),
  (3, 2, 1, 'FINALIZADO'),
  (4, 3, 2, 'FINALIZADO'),
  (5, 1, 2, 'FINALIZADO');